{% set version = "3.0.0" %}

package:
  name: dask-labextension
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/dask_labextension/dask_labextension-{{ version }}.tar.gz
  sha256: c613f5c76b8fce4fae167eeab3377e0706e5045a27da1200b3b173025a94d94b

build:
  number: 0
  noarch: python

outputs:
  - name: dask-labextension
    script: build_base.bat  # [win]
    script: build_base.sh  # [not win]
    requirements:
      host:
        - python >=3.5
        - pip
      run:
        - python >=3.5
        - bokeh >=1.0.0,!=2.0.0
        - distributed >=1.24.1
        - jupyter-server-proxy >=1.3.2
        - notebook >=4.3.1
    test:
      imports:
        - dask_labextension
      requires:
        - pip
      commands:
        - pip check

  - name: dask_labextension
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('dask-labextension', max_pin="x.x.x") }}
    test:
      imports:
        - dask_labextension

about:
  home: https://github.com/dask/dask-labextension
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A Jupyter Notebook server extension manages Dask clusters

extra:
  recipe-maintainers:
    - xhochy
    - ocefpaf
    - jsignell
